version: '3.7'

services:
    sulmun2yong-test-db:
        image: mysql:8.0.35
        container_name: sulmun2yong-test-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        expose:
            - "3340"
        ports:
            - "3340:3306"
        volumes:
            - sulmun2yong-test-db:/var/lib/mysql

    sulmun2yong-test-mongodb:
        image: mongo:latest
        container_name: sulmun2yong-test-mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        command:
            - mongod
            - --replSet
            - rs0
            - --keyFile
            - /data/keyfile/mongo-keyfile
            - --bind_ip_all
        expose:
            - "27017"
        ports:
            - "27017:27017"
        volumes:
            - sulmun2yong-test-mongodb:/data/db
            - ./mongo-keyfile:/data/keyfile/mongo-keyfile:ro

    sulmun2yong-test-redis:
        image: redis:latest
        container_name: sulmun2yong-test-redis
        restart: always
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        expose:
            - "6340"
        ports:
            - "6340:6379"
        volumes:
            - sulmun2yong-test-redis:/data

volumes:
    sulmun2yong-test-db:
    sulmun2yong-test-mongodb:
    sulmun2yong-test-redis:
