version: '3.7'

services:
    sulmun2yong-test-db:
        image: mysql:8.0.35
        container_name: sulmun2yong-test-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        expose:
            - "3307"
        ports:
            - "3307:3306"
        volumes:
            - sulmun2yong-test-db:/var/lib/mysql

    sulmun2yong-test-redis:
        image: redis:latest
        container_name: sulmun2yong-test-redis
        restart: always
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        expose:
            - "6379"
        ports:
            - "6379:6379"
        volumes:
            - sulmun2yong-test-redis:/data

volumes:
    sulmun2yong-test-db:
    sulmun2yong-test-redis:
