name: Docker Hub Push & 개발 서버 EC2 배포

on:
    push:
        branches:
            - develop
    workflow_dispatch: # 수동 실행 이벤트 추가

jobs:
    build:
        name: 빌드 작업
        runs-on: ubuntu-latest

        env:
            SECRET_YML_CONTENT: ${{ secrets.SECRET_YML_CONTENT }}
            JVM_XMS: ${{ secrets.DEVELOP_MIN_MEMORY }}
            JVM_XMX: ${{ secrets.DEVELOP_MAX_MEMORY }}
            DOCKER_ID: ${{ secrets.DOCKER_ID }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_BACKEND_IMAGE_NAME }}

        steps:
            - name: 코드 체크아웃
              uses: actions/checkout@v4

            - name: JDK 17 설정
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Gradle 설정
              uses: gradle/gradle-build-action@v2

            - name: application-secret.yml 등록
              run: |
                  echo "${SECRET_YML_CONTENT}" > common/src/main/resources/application-secret.yml

            - name: 환경 변수 설정
              run: |
                  echo DOCKER_ID="${{ env.DOCKER_ID }}" >> gradle.properties
                  echo DOCKER_PASSWORD="${{ env.DOCKER_PASSWORD }}" >> gradle.properties
                  echo DOCKER_IMAGE_NAME="${{ env.DOCKER_IMAGE_NAME }}" >> gradle.properties
                  echo JVM_XMS=${{ env.JVM_XMS }} >> gradle.properties
                  echo JVM_XMX=${{ env.JVM_XMX }} >> gradle.properties

            - name: Gradle로 빌드
              run: ./gradlew clean build

            - name: Docker Hub에 로그인
              run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_ID }}" --password-stdin

            - name: Web/Consumer Docker 이미지 빌드 및 푸시 (JIB)
              run: ./gradlew :survey-drawing:jib :consumer:jib -Ddocker.id="${{ env.DOCKER_ID }}" -Ddocker.password="${{ env.DOCKER_PASSWORD }}" -Ddocker.image.name="${{ env.DOCKER_IMAGE_NAME }}"
